name: .NET

on:
  push:
    tags: 
     - 2.*

jobs:
  build:
    name: 'Build Contractor'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile
    - name: Rename Artifact
      run: mv Contractor.CLI/bin/Publish/Contractor.CLI.exe Contractor.CLI/bin/Publish/contractor.exe
    - name: Zip Artifact
      run: zip -r ./contractor.zip .
      working-directory: ./Contractor.CLI/bin/Publish
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: contractor
        path: ./Contractor.CLI/bin/Publish/contractor.zip
        
  release:
    name: 'Create GitHub Release for Contractor'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:      
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: contractor
      - name: Get Tag Name
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./contractor.zip
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}

